@startuml


abstract Transaction<<abstract>> {
    +Execute()
}

class DepositTransaction
class WithdrawalTransaction
class TransferTransaction


interface DepositUI <<interface>>{
    +RequestDepositAmount()
}

interface WithdrawalUI <<interface>>{
    +RequestWithdrawalAmount()
}

interface TransferUI <<interface>>{
    +RequestTransferAmount()
}

interface UI <<interface>>{
    +RequestDepositAmount()
    +RequestWithdrawalAmount()
    +RequestTransferAmount()
}


hide members
show Transaction methods
show DepositUI methods
show TransferUI methods
show WithdrawalUI methods
show UI methods
DepositTransaction -up-|> Transaction
WithdrawalTransaction -up-|> Transaction
TransferTransaction -up-|> Transaction

DepositTransaction ..> DepositUI
WithdrawalTransaction ..> WithdrawalUI
TransferTransaction ..> TransferUI

UI -up-|> DepositUI
UI -up-|> WithdrawalUI
UI -up-|> TransferUI

@enduml